update documenter version and remove docs manifest
Since CI was complaining with:

```
ERROR: could not find entry with uuid 30578b45-9adc-5946-b283-645ec420af67 in manifest /home/runner/work/NetCDF.jl/NetCDF.jl/docs/Manifest.toml
```