fix EXCEPTION_ACCESS_VIOLATION whilst reading strings
Tests for me on Win64 would always fail with an access violation:

```
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7774f23c -- RtlAnsiStringToUnicodeString at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading C:\Users\visser_mn\.julia\v0.6\NetCDF\test\intermediate.jl, in expression starting on line 87
RtlAnsiStringToUnicodeString at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
free at C:\WINDOWS\system32\ucrtbase.DLL (unknown line)
nc_free_string at c:\OSGeo4W64\bin\netcdf.DLL (unknown line)
nc_free_string at C:\Users\visser_mn\.julia\v0.6\NetCDF\src\netcdf_c.jl:369
nc_get_vara_x! at C:\Users\visser_mn\.julia\v0.6\NetCDF\src\NetCDF.jl:292
```

The cause seems to be that `nc_free_string` is called on memory
that is allocated by julia. The julia GC should take care of it.